UI-changes
niharikadayama/cryptocurrency pull request #1
Opened 2022-05-12 11:47 UTC by niharikadayama

2022-05-12 12:03 UTC, aman-coditas requested changes

2022-05-12 12:03 UTC, aman-coditas commented on src/App.js
> -      <header className="App-header">
Create a header component in another file and import that here.

2022-05-12 12:05 UTC, aman-coditas requested changes

2022-05-12 12:05 UTC, aman-coditas commented on src/pages/homePage/index.js
> +        <div key="rank" className="col-1">
Shouldn't this be a part of the grid header?

2022-05-13 05:14 UTC, shreyas-coditas approved these changes

2022-05-13 05:15 UTC, merged